/**
 * services/claude.js
 *
 * In production: frontend calls /api/analyze (your own backend).
 * The backend holds ANTHROPIC_API_KEY in .env and proxies to Claude.
 * This prototype calls the API directly for demonstration purposes only.
 *
 * Mock mode is available when no API key is provided — uses pre-built
 * responses so the full workflow can be demonstrated without a live key.
 */

const MOCK_ANALYSIS = {
  overview:
    'Established mid-size manufacturer with a 25-year operating history. Revenue has grown at ~8% CAGR over the past three years. The company holds a strong regional reputation and has long-standing relationships with key clients in the semiconductor and industrial sectors.',
  risks:
    '• Customer concentration — top 3 clients represent approx. 65% of revenue\n• Key-man dependency on founding owner (retirement timeline unclear)\n• Capex backlog: equipment refresh estimated at NT$40–60M\n• Limited documented IP protection on core processes',
  valuation:
    'Based on comparable transactions in the Taiwan precision manufacturing sector, EV/EBITDA multiples range from 6x to 8x. Applying this to estimated EBITDA of NT$80–110M suggests an enterprise value of NT$480M–880M. A strategic premium of 10–20% is possible if the buyer values supply chain positioning.',
  buyers:
    '• Strategic buyers: domestic industrial groups seeking vertical integration or geographic expansion\n• Financial buyers: mid-market PE funds with 4–6 year hold horizon and manufacturing sector expertise\n• International: Japanese or Korean tier-1 suppliers expanding Taiwan supply chain presence',
  dd:
    '• Audited financial statements (3 years minimum)\n• Customer contracts — terms, renewal dates, concentration risk\n• Equipment register, maintenance records, capex schedule\n• Key personnel identification and retention risk\n• IP ownership, trade secrets, licensing agreements\n• Environmental compliance and liability history\n• Pension obligations and labour contracts\n• Pending litigation or regulatory issues',
};

const MOCK_MEMO = `INVESTMENT MEMO — [COMPANY NAME]
Prepared by: 168 M&A Platform (Demo Output)
Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

────────────────────────────────────────

1. EXECUTIVE SUMMARY

This memo summarises the investment opportunity for the acquisition of [Company Name], a Taiwan-based manufacturer with a strong regional market position and a stable revenue base. The transaction is structured as a full acquisition targeting a succession-driven exit by the founding owner.

2. COMPANY OVERVIEW

[Company Name] was established in [year] and operates in the precision manufacturing sector. The company serves clients across the semiconductor and industrial segments. Revenue has grown steadily at approximately 8% CAGR, with EBITDA margins in the 18–22% range.

3. KEY INVESTMENT CONSIDERATIONS

Strengths
• Long-standing client relationships with blue-chip customers
• Strong technical reputation and skilled workforce
• Stable cash generation with low debt

Risks
• Customer concentration (top 3 clients = 65% of revenue)
• Key-man dependency on founder
• Capex requirements for equipment refresh

4. VALUATION

Based on comparable transactions, an EV/EBITDA multiple of 6–8x implies an enterprise value of NT$480M–880M. Recommended offer range: NT$600M–750M, subject to due diligence findings.

5. RECOMMENDED NEXT STEPS

• Initiate management meeting with founder
• Commission financial and legal due diligence
• Prepare binding LOI with agreed exclusivity period
• Identify and approach strategic buyer shortlist

────────────────────────────────────────
This document is generated by 168 M&A Platform (prototype demo).
All figures are illustrative and require verification through due diligence.`;

const MOCK_MANUS = {
  website: 'Company website active — last updated Q1 2026',
  news: '2 recent mentions found: industry award (Mar 2026), supplier partnership announcement (Jan 2026)',
  registry: 'Business registration active. Paid-in capital NT$50M. No insolvency filings.',
  industry: 'Sector: Precision Manufacturing · TPEX comparable peers: 4 identified',
};

// ─── Safe JSON parser ────────────────────────────────────────────────────────
function safeParseAnalysis(raw) {
  try {
    const cleaned = raw
      .replace(/```json|```/g, '')
      .trim();
    const match = cleaned.match(/\{[\s\S]*\}/);
    if (match) return JSON.parse(match[0]);
    return JSON.parse(cleaned);
  } catch {
    return {
      overview: raw,
      risks: '—',
      valuation: '—',
      buyers: '—',
      dd: '—',
    };
  }
}

// ─── Mock Manus enrichment (simulated delay) ─────────────────────────────────
async function runManusEnrichment(companyName) {
  await new Promise(r => setTimeout(r, 1800));
  return { ...MOCK_MANUS, company: companyName };
}

// ─── Claude call (direct in prototype; should be proxied in production) ──────
async function callClaude(messages, system, apiKey) {
  if (!apiKey || !apiKey.startsWith('sk-ant-')) {
    // Mock mode
    await new Promise(r => setTimeout(r, 2200));
    return JSON.stringify(MOCK_ANALYSIS);
  }

  /**
   * PRODUCTION NOTE:
   * Replace this fetch with a call to your own backend:
   *   POST /api/analyze  →  { messages, system }
   * The backend stores ANTHROPIC_API_KEY in .env and proxies to Anthropic.
   * This avoids exposing the key in the browser.
   */
  const res = await fetch('http://localhost:3000/api/analyze', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: 'claude-sonnet-4-5',
      max_tokens: 2000,
      system: system || '',
      messages,
    }),
  });

  if (!res.ok) {
    const e = await res.json();
    throw new Error(e.error?.message || 'API Error ' + res.status);
  }

  const d = await res.json();
  const raw = d.content.map(c => c.text || '').join('');
  const cleaned = raw.replace(/```json\s*/g, '').replace(/```\s*/g, '').trim();
  console.log('Claude cleaned output:', cleaned);
  return cleaned;
}

async function callClaudeMemo(messages, apiKey) {
  if (!apiKey || !apiKey.startsWith('sk-ant-')) {
    await new Promise(r => setTimeout(r, 2000));
    return MOCK_MEMO;
  }

  const res = await fetch('http://localhost:3000/api/analyze', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: 'claude-sonnet-4-5',
      max_tokens: 2000,
      system: '你是資深併購顧問，專精台灣中小企業併購交易。請用繁體中文撰寫專業的併購文件，格式清晰，語氣專業。',
      messages,
    }),
  });

  if (!res.ok) {
    const e = await res.json();
    throw new Error(e.error?.message || 'API Error ' + res.status);
  }

  const d = await res.json();
  if (!d.content) throw new Error(JSON.stringify(d));
  return d.content.map(c => c.text || '').join('');
}
